name: Build Linux

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-linux, arm64-linux]
        include:
          - target: x86_64-linux
            rust_target: x86_64-unknown-linux-gnu
          - target: arm64-linux
            rust_target: aarch64-unknown-linux-gnu
            cross_compile: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup ARM64 toolchain
        if: matrix.target == 'arm64-linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu

      - name: Build
        run: |
          if [ "${{ matrix.target }}" = "arm64-linux" ]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          fi
          cargo build --release --target ${{ matrix.rust_target }}
          mkdir -p release
          cp target/${{ matrix.rust_target }}/release/smtp2tg release/smtp2tg-${{ matrix.target }}

      - name: Create checksum
        run: |
          cd release
          sha256sum smtp2tg-${{ matrix.target }} > smtp2tg-${{ matrix.target }}.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smtp2tg-${{ matrix.target }}
          path: |
            release/smtp2tg-${{ matrix.target }}
            release/smtp2tg-${{ matrix.target }}.sha256

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release
        run: |
          mkdir -p release_assets
          find artifacts -type f -exec cp {} release_assets/ \;
          cd release_assets
          tar -czvf smtp2tg-x86_64-linux.tar.gz smtp2tg-x86_64-linux
          tar -czvf smtp2tg-arm64-linux.tar.gz smtp2tg-arm64-linux

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release_assets/*.tar.gz
            release_assets/*.sha256
