name: Build and Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:  # Allows manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    continue-on-error: false  # Ensures one failure cancels others
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
        include:
          - target: x86_64-unknown-linux-gnu
            docker-platform: linux/amd64
          - target: aarch64-unknown-linux-gnu
            docker-platform: linux/arm64
    
    steps:
      - uses: actions/checkout@v4

      # Fixed: Use modern Rust setup action
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: rust-src

      # Fixed: Explicit cross-compilation setup
      - name: Setup cross-compilation
        run: |
          sudo apt-get update
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi
          rustup target add ${{ matrix.target }}

      - name: Build release binary
        run: |
          cargo build --release --target ${{ matrix.target }}
          mkdir -p dist
          cp target/${{ matrix.target }}/release/smtp2tg dist/smtp2tg-${{ matrix.target }}

      - name: Create checksum
        run: |
          cd dist
          sha256sum smtp2tg-${{ matrix.target }} > smtp2tg-${{ matrix.target }}.sha256

      - name: Compress artifacts
        run: |
          cd dist
          tar -czvf smtp2tg-${{ matrix.target }}.tar.gz smtp2tg-${{ matrix.target }} smtp2tg-${{ matrix.target }}.sha256

      # Fixed: Updated artifact upload action
      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # Changed from v3
        with:
          name: smtp2tg-${{ matrix.target }}
          path: dist/smtp2tg-${{ matrix.target }}.tar.gz
          retention-days: 5

  create-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4  # Changed from v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body: "Pre-built binaries for ${{ github.ref_name }}"
          files: |
            artifacts/smtp2tg-x86_64-unknown-linux-gnu.tar.gz
            artifacts/smtp2tg-aarch64-unknown-linux-gnu.tar.gz
