name: Build and Release (Single Platform)

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for x86_64 Linux
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: |
          cargo build --release
          mkdir -p release
          cp target/release/smtp2tg release/smtp2tg-x86_64-linux

      - name: Create checksum
        run: |
          cd release
          sha256sum smtp2tg-x86_64-linux > smtp2tg-x86_64-linux.sha256

      - name: Compress artifact
        run: |
          cd release
          tar -czvf smtp2tg-x86_64-linux.tar.gz smtp2tg-x86_64-linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smtp2tg-x86_64-linux  # Unique artifact name
          path: |
            release/smtp2tg-x86_64-linux.tar.gz
            release/smtp2tg-x86_64-linux.sha256
          retention-days: 1

  create-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: smtp2tg-*

      - name: Show files for debugging
        run: |
          ls -la artifacts/
          cat artifacts/*.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Pre-built binary for ${{ github.ref_name }}
            
            SHA256 Checksum:
            ```
            $(cat artifacts/smtp2tg-x86_64-linux.sha256)
            ```
          files: |
            artifacts/smtp2tg-x86_64-linux.tar.gz
            artifacts/smtp2tg-x86_64-linux.sha256
          draft: false
          prerelease: false
