name: Build and Release

on:
  push:
    tags: ['v*']  # Triggers on tags like v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Add cross-compilation support
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu  # ARM64 support
          rustup target add ${{ matrix.target }}

      - name: Build release binary
        run: |
          cargo build --release --target ${{ matrix.target }}
          mkdir -p dist
          cp target/${{ matrix.target }}/release/smtp2tg dist/smtp2tg-${{ matrix.target }}

      - name: Create checksum
        run: |
          cd dist
          sha256sum smtp2tg-${{ matrix.target }} > smtp2tg-${{ matrix.target }}.sha256

      - name: Compress artifacts
        run: |
          cd dist
          tar -czvf smtp2tg-${{ matrix.target }}.tar.gz smtp2tg-${{ matrix.target }} smtp2tg-${{ matrix.target }}.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: smtp2tg-${{ matrix.target }}
          path: dist/smtp2tg-${{ matrix.target }}.tar.gz

  create-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body: "Pre-built binaries for ${{ github.ref_name }}"
          files: |
            artifacts/smtp2tg-x86_64-unknown-linux-gnu.tar.gz
            artifacts/smtp2tg-aarch64-unknown-linux-gnu.tar.gz
          draft: false
          prerelease: false
