name: Build and Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: rust-src

      # ARM64 specific setup
      - name: Setup cross-compilation
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu

      - name: Build release binary
        run: |
          # Disable default features to prevent accidental SSL inclusion
          cargo build --release --target ${{ matrix.target }} --no-default-features
          mkdir -p dist
          cp target/${{ matrix.target }}/release/smtp2tg dist/smtp2tg-${{ matrix.target }}

      - name: Create checksum
        run: |
          cd dist
          sha256sum smtp2tg-${{ matrix.target }} > smtp2tg-${{ matrix.target }}.sha256

      - name: Compress artifacts
        run: |
          cd dist
          tar -czvf smtp2tg-${{ matrix.target }}.tar.gz smtp2tg-${{ matrix.target }} smtp2tg-${{ matrix.target }}.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smtp2tg-${{ matrix.target }}
          path: dist/smtp2tg-${{ matrix.target }}.tar.gz

  create-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          files: |
            artifacts/smtp2tg-x86_64-unknown-linux-gnu.tar.gz
            artifacts/smtp2tg-aarch64-unknown-linux-gnu.tar.gz
